#!/bin/sh
# chkconfig: 99 1
# description: nicofav init script
# processname: nicofav
# pidfile:     /var/run/nicofav.pid

# Source function library.
if [ -f /etc/rc.d/init.d/functions ]; then
  . /etc/rc.d/init.d/functions
fi

nicohome="/usr/share/nico-fav-tweet"
nico="${nicohome}/bin/nico-fav-tweet"
prog=nicofav
pidfile="/var/run/${prog}.pid"

user=nicofav

RETVAL=0

eval_cmd() {
  local rc=$1
  if [ $rc -eq 0 ]; then
    echo '[  OK  ]'
  else
    echo '[FAILED]'
  fi
  return $rc
}

start() {
  if [ -f $pidfile ] ; then
    echo "${prog} is running."
    exit 1;
  fi
  echo -n "Starting $prog: "
  if [ -f /etc/rc.d/init.d/functions ]; then
      daemon --user $user $nico 2>> /tmp/nico-error.log &
    else
      su - $user -c "${nico} 2>> /tmp/nico-error.log &"
  fi
  echo $! > $pidfile
  pidof $nico >/dev/null 2>&1
  eval_cmd 0
  RETVAL=$?
}

stop() {
  echo -n $"Stopping $prog: "
  local pid=$(pidof $nico)
  if [ -z "${pid}" ]; then
    echo "$prog not running"
    return 0
  fi
  rm -f $pidfile
  kill -9 $pid
  eval_cmd $?
  RETVAL=$?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status $prog
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload}"
        exit 1
esac

exit $RETVAL
